# Change these first
owner: upptime # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Adarsh Vihar
    url: https://cloud.tymly.in/status/1041

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /tymlymonitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: tymly monitor
  introTitle: "**tymly monitor ** is the uptime monitor and status page for tymly smart boards."
  introMessage: This is the status page for tymly smart notice boards.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
