# Change these first
owner: bvenkysubbu # Your GitHub username
repo: tymlymonitor # Your GitHub repository name

# Add your sites here
sites:
  - name: Prestige Jade Pavilion Tower 1
    url: https://cloud.tymly.in/status/1172
    __dangerous__body_degraded: '{"status": "down"}'  
  - name: Prestige Jade Pavilion Tower 2
    url: https://cloud.tymly.in/status/1173
    __dangerous__body_degraded: '{"status": "down"}'  
  - name: Prestige Jade Pavilion Tower 3
    url: https://cloud.tymly.in/status/1171
    __dangerous__body_degraded: '{"status": "down"}'  
  - name: Prestige Jade Pavilion Tower 4
    url: https://cloud.tymly.in/status/1170
    __dangerous__body_degraded: '{"status": "down"}'  
  - name: Trifecta Esplanade Clubhouse
    url: https://cloud.tymly.in/status/1167
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade Security
    url: https://cloud.tymly.in/status/1168
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade Multipurpose Hall
    url: https://cloud.tymly.in/status/1169
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Casa Gopalan Block B Lift
    url: https://cloud.tymly.in/status/1005
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Casa Gopalan Block A Lift
    url: https://cloud.tymly.in/status/1006
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Gayathri Goodlife
    url: https://cloud.tymly.in/status/1009
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Amrutha Value
    url: https://cloud.tymly.in/status/1010
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sterling Shalom C Block
    url: https://cloud.tymly.in/status/1011
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sterling Shalom D Block
    url: https://cloud.tymly.in/status/1012
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sterling Shalom F Block
    url: https://cloud.tymly.in/status/1013
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sai Raghavendras Bloomfields
    url: https://cloud.tymly.in/status/1014
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Amrutha Sarovar
    url: https://cloud.tymly.in/status/1016
    __dangerous__body_degraded: '{"status": "down"}'
  - name: SBB Touchstone Reborn
    url: https://cloud.tymly.in/status/1018
    __dangerous__body_degraded: '{"status": "down"}'
  - name: United Elysium
    url: https://cloud.tymly.in/status/1019
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Greenville Whitefield
    url: https://cloud.tymly.in/status/1020
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sunshine Silicon Citi
    url: https://cloud.tymly.in/status/1021
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Nitesh Forest Hills and Flush Meadows
    url: https://cloud.tymly.in/status/1023
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sterling Shalom A Block
    url: https://cloud.tymly.in/status/1024
    __dangerous__body_degraded: '{"status": "down"}'
  - name: DSR Sunrise Towers
    url: https://cloud.tymly.in/status/1025
    __dangerous__body_degraded: '{"status": "down"}'
  - name: United Elysium 2
    url: https://cloud.tymly.in/status/1026
    __dangerous__body_degraded: '{"status": "down"}'
  - name: DSR Sunrise Towers 2
    url: https://cloud.tymly.in/status/1027
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Adithya Pristine KMC
    url: https://cloud.tymly.in/status/1028
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sraddha Whitecliff
    url: https://cloud.tymly.in/status/1033
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sraddha Whitecliff 2
    url: https://cloud.tymly.in/status/1034
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sraddha Whitecliff 3
    url: https://cloud.tymly.in/status/1035
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sowparnika Ananda
    url: https://cloud.tymly.in/status/1036
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Wilson Vintage 1
    url: https://cloud.tymly.in/status/1037
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Wilson Vintage 2
    url: https://cloud.tymly.in/status/1038
    __dangerous__body_degraded: '{"status": "down"}'
  - name: SNR Silver Ripples
    url: https://cloud.tymly.in/status/1039
    __dangerous__body_degraded: '{"status": "down"}'
  - name: SNR Silver Ripples 2
    url: https://cloud.tymly.in/status/1040
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Adarsh Vihar
    url: https://cloud.tymly.in/status/1041
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Urban Greens
    url: https://cloud.tymly.in/status/1046
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Nitesh Flushing Meadows Block B
    url: https://cloud.tymly.in/status/1047
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Ruchira Lilium v2
    url: https://cloud.tymly.in/status/1048
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Nitesh Flushing Meadows Block D
    url: https://cloud.tymly.in/status/1049
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Nitesh Forest Hills Block C
    url: https://cloud.tymly.in/status/1050
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Nitesh Forest Hills Block B
    url: https://cloud.tymly.in/status/1051
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Nitesh Forest Hills Block A
    url: https://cloud.tymly.in/status/1052
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Nitesh Flushing Meadows Block A
    url: https://cloud.tymly.in/status/1053
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Nitesh Flushing Meadows Block C
    url: https://cloud.tymly.in/status/1054
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Prakruthi Villas Sarjapura
    url: https://cloud.tymly.in/status/1058
    __dangerous__body_degraded: '{"status": "down"}'
  - name: PSR Aster 1
    url: https://cloud.tymly.in/status/1059
    __dangerous__body_degraded: '{"status": "down"}'
  - name: PSR Aster 2 G Block
    url: https://cloud.tymly.in/status/1060
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sowparnika Ananda D Block
    url: https://cloud.tymly.in/status/1061
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Balaji Sunflower
    url: https://cloud.tymly.in/status/1062
    __dangerous__body_degraded: '{"status": "down"}'
  - name: PSR Aster 3 E Block
    url: https://cloud.tymly.in/status/1064
    __dangerous__body_degraded: '{"status": "down"}'
  - name: PSR Aster 4 C Block
    url: https://cloud.tymly.in/status/1065
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sai Gardens
    url: https://cloud.tymly.in/status/1066
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Hinduja Park 1
    url: https://cloud.tymly.in/status/1067
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sterling Villa Grande
    url: https://cloud.tymly.in/status/1068
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sterling Shalom B Block
    url: https://cloud.tymly.in/status/1069
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sterling Shalom E Block
    url: https://cloud.tymly.in/status/1070
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sai Gardens Community Hall
    url: https://cloud.tymly.in/status/1073
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sai Gardens Temple Side
    url: https://cloud.tymly.in/status/1074
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Mahaveer Varna A1
    url: https://cloud.tymly.in/status/1083
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Mahaveer Varna A4
    url: https://cloud.tymly.in/status/1084
    expectedStatusCodes:
      - 200
      - 521
  - name: Mahaveer Varna B1
    url: https://cloud.tymly.in/status/1085
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Mahaveer Varna B3
    url: https://cloud.tymly.in/status/1086
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sumadhura Silver Ripples Club House
    url: https://cloud.tymly.in/status/1090
    __dangerous__body_degraded: '{"status": "down"}'
  - name: SMR Vinay Cascade B Block
    url: https://cloud.tymly.in/status/1093
    __dangerous__body_degraded: '{"status": "down"}'
  - name: SMR Vinay Cascade A Block
    url: https://cloud.tymly.in/status/1094
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Whitestone Landmark
    url: https://cloud.tymly.in/status/1095
    __dangerous__body_degraded: '{"status": "down"}'
  - name: White Breeze 1
    url: https://cloud.tymly.in/status/1096
    __dangerous__body_degraded: '{"status": "down"}'
  - name: White Breeze 2
    url: https://cloud.tymly.in/status/1097
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sowparnika Swastika 2
    url: https://cloud.tymly.in/status/1099
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Prestige Lakeside Habitat Tower 13
    url: https://cloud.tymly.in/status/1100
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sowparnika Swastika 1
    url: https://cloud.tymly.in/status/1101
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Prestige Lakeside Habitat Tower 1
    url: https://cloud.tymly.in/status/1102
    expectedStatusCodes:
      - 200
      - 521
  - name: Prestige Lakeside Habitat Tower 2 and 3
    url: https://cloud.tymly.in/status/1103
    expectedStatusCodes:
      - 200
      - 521
  - name: Prestige Lakeside Habitat Tower 4
    url: https://cloud.tymly.in/status/1104
    expectedStatusCodes:
      - 200
      - 521
  - name: Prestige Lakeside Habitat Tower 5 and 6
    url: https://cloud.tymly.in/status/1105
    expectedStatusCodes:
      - 200
      - 521
  - name: Prestige Lakeside Habitat Tower 7 and 8
    url: https://cloud.tymly.in/status/1106
    expectedStatusCodes:
      - 200
      - 521
  - name: Prestige Lakeside Habitat Tower 12
    url: https://cloud.tymly.in/status/1107
    expectedStatusCodes:
      - 200
      - 521
  - name: Prestige Lakeside Habitat Tower 14
    url: https://cloud.tymly.in/status/1108
    expectedStatusCodes:
      - 200
      - 521
  - name: Prestige Lakeside Habitat Tower 15 and 16
    url: https://cloud.tymly.in/status/1109
    expectedStatusCodes:
      - 200
      - 521
  - name: Prestige Lakeside Habitat Tower 17
    url: https://cloud.tymly.in/status/1110
    expectedStatusCodes:
      - 200
      - 521
  - name: Prestige Lakeside Habitat Tower 18
    url: https://cloud.tymly.in/status/1111
    expectedStatusCodes:
      - 200
      - 521
  - name: Prestige Lakeside Habitat Tower 19
    url: https://cloud.tymly.in/status/1112
    expectedStatusCodes:
      - 200
      - 521
  - name: Prestige Lakeside Habitat Tower 20
    url: https://cloud.tymly.in/status/1113
    expectedStatusCodes:
      - 200
      - 521
  - name: Prestige Lakeside Habitat Tower 21
    url: https://cloud.tymly.in/status/1114
    expectedStatusCodes:
      - 200
      - 521
  - name: Prestige Lakeside Habitat Tower 22
    url: https://cloud.tymly.in/status/1115
    expectedStatusCodes:
      - 200
      - 521
  - name: Prestige Lakeside Habitat Tower 9
    url: https://cloud.tymly.in/status/1116
    expectedStatusCodes:
      - 200
      - 521
  - name: Prestige Lakeside Habitat Tower 10
    url: https://cloud.tymly.in/status/1117
    expectedStatusCodes:
      - 200
      - 521
  - name: Prestige Lakeside Habitat Tower 11
    url: https://cloud.tymly.in/status/1118
    expectedStatusCodes:
      - 200
      - 521
  - name: Prestige Lakeside Habitat Tower 23
    url: https://cloud.tymly.in/status/1119
    expectedStatusCodes:
      - 200
      - 521
  - name: Prestige Lakeside Habitat Tower 24
    url: https://cloud.tymly.in/status/1120
    expectedStatusCodes:
      - 200
      - 521
  - name: VBHC Serene Town A Block
    url: https://cloud.tymly.in/status/1129
    __dangerous__body_degraded: '{"status": "down"}'
  - name: VBHC Serene Town B Block
    url: https://cloud.tymly.in/status/1130
    __dangerous__body_degraded: '{"status": "down"}'
  - name: VBHC Serene Town D Block
    url: https://cloud.tymly.in/status/1131
    __dangerous__body_degraded: '{"status": "down"}'
  - name: VBHC Serene Town C Block
    url: https://cloud.tymly.in/status/1132
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Desai Grandeur 1
    url: https://cloud.tymly.in/status/1133
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Desai Grandeur 2
    url: https://cloud.tymly.in/status/1134
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Madhuban Brindavan A Block
    url: https://cloud.tymly.in/status/1135
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Madhuban Brindavan B Block
    url: https://cloud.tymly.in/status/1136
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Dasta Concerto Entrance
    url: https://cloud.tymly.in/status/1137
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Dasta Concerto Basement
    url: https://cloud.tymly.in/status/1138
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sunshine Silicon Citi 2
    url: https://cloud.tymly.in/status/1139
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Amrutha Sarovar Office
    url: https://cloud.tymly.in/status/1140
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Brigade Cosmopolis Clubhouse Entrance
    url: https://cloud.tymly.in/status/1141
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sterling Ascentia Tower 6
    url: https://cloud.tymly.in/status/1142
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sterling Ascentia Tower 5
    url: https://cloud.tymly.in/status/1143
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Brigade Cosmopolis Clubhouse End
    url: https://cloud.tymly.in/status/1145
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade A Block
    url: https://cloud.tymly.in/status/1153
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade B Block
    url: https://cloud.tymly.in/status/1154
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade C Block
    url: https://cloud.tymly.in/status/1155
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade D Block
    url: https://cloud.tymly.in/status/1156
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade E Block
    url: https://cloud.tymly.in/status/1157
    expectedStatusCodes:
      - 200
      - 521
  - name: Trifecta Esplanade F Block
    url: https://cloud.tymly.in/status/1159
    expectedStatusCodes:
      - 200
      - 521
  - name: Trifecta Esplanade G Block
    url: https://cloud.tymly.in/status/1158
    expectedStatusCodes:
      - 200
      - 521
  - name: Trifecta Esplanade H Block
    url: https://cloud.tymly.in/status/1161
    expectedStatusCodes:
      - 200
      - 521
  - name: Trifecta Esplanade I Block
    url: https://cloud.tymly.in/status/1160
    expectedStatusCodes:
      - 200
      - 521
  - name: Trifecta Esplanade J Block
    url: https://cloud.tymly.in/status/1162
    expectedStatusCodes:
      - 200
      - 521
  - name: Trifecta Esplanade K Block
    url: https://cloud.tymly.in/status/1163
    expectedStatusCodes:
      - 200
      - 521
  - name: Trifecta Esplanade L Block
    url: https://cloud.tymly.in/status/1164
    expectedStatusCodes:
      - 200
      - 521
  - name: Trifecta Esplanade M Block
    url: https://cloud.tymly.in/status/1003
    expectedStatusCodes:
      - 200
      - 521
  - name: Trifecta Esplanade N Block
    url: https://cloud.tymly.in/status/1165
    expectedStatusCodes:
      - 200
      - 521
  - name: Trifecta Esplanade O Block
    url: https://cloud.tymly.in/status/1166
    expectedStatusCodes:
      - 200
      - 521
  - name: Trifecta Esplanade P Block
    url: https://cloud.tymly.in/status/1017
    __dangerous__body_degraded: '{"status": "down"}'
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /tymlymonitor
  logoUrl: https://tymly.in/img/tymly_logo.png
  name: tymly monitor
  introTitle: "**tymly monitor ** is the uptime monitor and status page for tymly smart boards."
  introMessage: This is the status page for tymly smart notice boards.
  navbar:
    - title: Status
      href: /
  js: "function contains(t,n){var e=document.querySelectorAll(t);return Array.prototype.filter.call(e,function(t){return RegExp(n).test(t.textContent)})}window.onload = function() {setTimeout(function(){foundDivsActiveIncidents=contains('section','Active Incidents');foundDivsActiveIncidents[0].remove();foundDivsPastIncidents=contains('section','Past Incidents');foundDivsPastIncidents[0].remove();}, 5000);}"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
