# Change these first
owner: bvenkysubbu # Your GitHub username
repo: tymlymonitor # Your GitHub repository name

# Add your sites here
sites:
  - name: SMD Altezz Block A
    url: https://cloud.tymly.in/status/1175
    __dangerous__body_degraded: '{"status": "down"}'  
  - name: SMD Altezz Block B
    url: https://cloud.tymly.in/status/1176
    __dangerous__body_degraded: '{"status": "down"}'  
  - name: SMD Altezz Block C
    url: https://cloud.tymly.in/status/1177
    __dangerous__body_degraded: '{"status": "down"}'  
  - name: SMD Altezz Clubhouse
    url: https://cloud.tymly.in/status/1178
    __dangerous__body_degraded: '{"status": "down"}'
  - name: SMD Altezz Block A Basement
    url: https://cloud.tymly.in/status/1205
    __dangerous__body_degraded: '{"status": "down"}'  
  - name: SMD Altezz Block B Basement
    url: https://cloud.tymly.in/status/1204
    __dangerous__body_degraded: '{"status": "down"}'  
  - name: SMD Altezz Block C Basement
    url: https://cloud.tymly.in/status/1203
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Prestige Jade Pavilion Tower 1
    url: https://cloud.tymly.in/status/1172
    __dangerous__body_degraded: '{"status": "down"}'  
  - name: Prestige Jade Pavilion Tower 2
    url: https://cloud.tymly.in/status/1173
    __dangerous__body_degraded: '{"status": "down"}'  
  - name: Prestige Jade Pavilion Tower 3
    url: https://cloud.tymly.in/status/1171
    __dangerous__body_degraded: '{"status": "down"}'  
  - name: Prestige Jade Pavilion Tower 4
    url: https://cloud.tymly.in/status/1170
    __dangerous__body_degraded: '{"status": "down"}'  
  - name: Trifecta Esplanade Clubhouse
    url: https://cloud.tymly.in/status/1167
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade Security
    url: https://cloud.tymly.in/status/1168
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade Multipurpose Hall
    url: https://cloud.tymly.in/status/1169
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Casa Gopalan Block B Lift
    url: https://cloud.tymly.in/status/1005
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Casa Gopalan Block A Lift
    url: https://cloud.tymly.in/status/1006
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Casa Gopalan Basement 2
    url: https://cloud.tymly.in/status/1190
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Casa Gopalan Block B Ground Floor
    url: https://cloud.tymly.in/status/1191
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Casa Gopalan Block A Ground Floor
    url: https://cloud.tymly.in/status/1206
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Amrutha Value
    url: https://cloud.tymly.in/status/1010
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sterling Shalom C Block
    url: https://cloud.tymly.in/status/1011
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sterling Shalom D Block
    url: https://cloud.tymly.in/status/1012
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sterling Shalom F Block
    url: https://cloud.tymly.in/status/1013
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sai Raghavendras Bloomfields
    url: https://cloud.tymly.in/status/1014
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Amrutha Sarovar
    url: https://cloud.tymly.in/status/1016
    __dangerous__body_degraded: '{"status": "down"}'
  - name: SBB Touchstone B Block
    url: https://cloud.tymly.in/status/1018
    __dangerous__body_degraded: '{"status": "down"}'
  - name: SBB Touchstone C Block
    url: https://cloud.tymly.in/status/1184
    __dangerous__body_degraded: '{"status": "down"}'
  - name: SBB Touchstone D Block
    url: https://cloud.tymly.in/status/1185
    __dangerous__body_degraded: '{"status": "down"}'
  - name: SBB Touchstone A1 Block
    url: https://cloud.tymly.in/status/1186
    __dangerous__body_degraded: '{"status": "down"}'
  - name: SBB Touchstone A2 Block
    url: https://cloud.tymly.in/status/1187
    __dangerous__body_degraded: '{"status": "down"}'
  - name: United Elysium
    url: https://cloud.tymly.in/status/1019
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Greenville Whitefield
    url: https://cloud.tymly.in/status/1020
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Nitesh Forest Hills and Flush Meadows
    url: https://cloud.tymly.in/status/1023
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sterling Shalom A Block
    url: https://cloud.tymly.in/status/1024
    __dangerous__body_degraded: '{"status": "down"}'
  - name: DSR Sunrise Towers
    url: https://cloud.tymly.in/status/1025
    __dangerous__body_degraded: '{"status": "down"}'
  - name: United Elysium 2
    url: https://cloud.tymly.in/status/1026
    __dangerous__body_degraded: '{"status": "down"}'
  - name: DSR Sunrise Towers 2
    url: https://cloud.tymly.in/status/1027
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Adithya Pristine KMC
    url: https://cloud.tymly.in/status/1028
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sowparnika Ananda
    url: https://cloud.tymly.in/status/1036
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Wilson Vintage 1
    url: https://cloud.tymly.in/status/1037
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Wilson Vintage 2
    url: https://cloud.tymly.in/status/1038
    __dangerous__body_degraded: '{"status": "down"}'
  - name: SNR Silver Ripples
    url: https://cloud.tymly.in/status/1039
    __dangerous__body_degraded: '{"status": "down"}'
  - name: SNR Silver Ripples 2
    url: https://cloud.tymly.in/status/1040
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Adarsh Vihar
    url: https://cloud.tymly.in/status/1041
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Urban Greens
    url: https://cloud.tymly.in/status/1046
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Nitesh Flushing Meadows Block B
    url: https://cloud.tymly.in/status/1047
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Ruchira Lilium v2
    url: https://cloud.tymly.in/status/1048
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Nitesh Flushing Meadows Block D
    url: https://cloud.tymly.in/status/1049
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Nitesh Forest Hills Block C
    url: https://cloud.tymly.in/status/1050
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Nitesh Forest Hills Block B
    url: https://cloud.tymly.in/status/1051
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Nitesh Forest Hills Block A
    url: https://cloud.tymly.in/status/1052
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Nitesh Flushing Meadows Block A
    url: https://cloud.tymly.in/status/1053
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Nitesh Flushing Meadows Block C
    url: https://cloud.tymly.in/status/1054
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Prakruthi Villas Sarjapura
    url: https://cloud.tymly.in/status/1058
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sowparnika Ananda D Block
    url: https://cloud.tymly.in/status/1061
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Balaji Sunflower
    url: https://cloud.tymly.in/status/1062
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sri Balaji Sunflower A Block
    url: https://cloud.tymly.in/status/1062
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sri Balaji Sunflower B Block
    url: https://cloud.tymly.in/status/1062
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sri Balaji Sunflower C Block
    url: https://cloud.tymly.in/status/1062
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sai Gardens
    url: https://cloud.tymly.in/status/1066
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sai Gardens Community Hall
    url: https://cloud.tymly.in/status/1073
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sai Gardens Temple Side
    url: https://cloud.tymly.in/status/1074
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sai Gardens Shanthi II
    url: https://cloud.tymly.in/status/1193
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sai Gardens Dharma 8
    url: https://cloud.tymly.in/status/1194
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sai Gardens Prema 2
    url: https://cloud.tymly.in/status/1195
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sai Gardens Sathya 2
    url: https://cloud.tymly.in/status/1196
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sai Gardens Sathya 5
    url: https://cloud.tymly.in/status/1197
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sai Gardens Shanthi 3
    url: https://cloud.tymly.in/status/1198
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sai Gardens Dharma 5
    url: https://cloud.tymly.in/status/1199
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sai Gardens Dharma 2
    url: https://cloud.tymly.in/status/1200
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sai Gardens Sathya 6
    url: https://cloud.tymly.in/status/1202
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Hinduja Park 1
    url: https://cloud.tymly.in/status/1067
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sterling Villa Grande
    url: https://cloud.tymly.in/status/1068
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sterling Shalom B Block
    url: https://cloud.tymly.in/status/1069
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sterling Shalom E Block
    url: https://cloud.tymly.in/status/1070
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Mahaveer Varna A1
    url: https://cloud.tymly.in/status/1083
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Mahaveer Varna A4
    url: https://cloud.tymly.in/status/1084
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Mahaveer Varna B1
    url: https://cloud.tymly.in/status/1085
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Mahaveer Varna B3
    url: https://cloud.tymly.in/status/1086
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Sumadhura Silver Ripples Club House
    url: https://cloud.tymly.in/status/1090
    __dangerous__body_degraded: '{"status": "down"}'
  - name: SMR Vinay Cascade B Block
    url: https://cloud.tymly.in/status/1093
    __dangerous__body_degraded: '{"status": "down"}'
  - name: SMR Vinay Cascade A Block
    url: https://cloud.tymly.in/status/1094
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Whitestone Landmark
    url: https://cloud.tymly.in/status/1095
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Whitestone Landmark Block A
    url: https://cloud.tymly.in/status/1192
    __dangerous__body_degraded: '{"status": "down"}'
  - name: White Breeze 1
    url: https://cloud.tymly.in/status/1096
    __dangerous__body_degraded: '{"status": "down"}'
  - name: White Breeze 2
    url: https://cloud.tymly.in/status/1097
    __dangerous__body_degraded: '{"status": "down"}'
  - name: VBHC Serene Town A Block
    url: https://cloud.tymly.in/status/1129
    __dangerous__body_degraded: '{"status": "down"}'
  - name: VBHC Serene Town B Block
    url: https://cloud.tymly.in/status/1130
    __dangerous__body_degraded: '{"status": "down"}'
  - name: VBHC Serene Town D Block
    url: https://cloud.tymly.in/status/1131
    __dangerous__body_degraded: '{"status": "down"}'
  - name: VBHC Serene Town C Block
    url: https://cloud.tymly.in/status/1132
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Desai Grandeur 1
    url: https://cloud.tymly.in/status/1133
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Desai Grandeur 2
    url: https://cloud.tymly.in/status/1134
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Madhuban Brindavan A Block
    url: https://cloud.tymly.in/status/1135
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Madhuban Brindavan B Block
    url: https://cloud.tymly.in/status/1136
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Madhuban Brindavan 3 Block
    url: https://cloud.tymly.in/status/1182
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Madhuban Brindavan 4 Block
    url: https://cloud.tymly.in/status/1183
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Dasta Concerto Entrance
    url: https://cloud.tymly.in/status/1137
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Dasta Concerto Basement
    url: https://cloud.tymly.in/status/1138
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Dasta Concerto Basement 2
    url: https://cloud.tymly.in/status/1188
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Dasta Concerto Clubhouse Gym
    url: https://cloud.tymly.in/status/1189
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Amrutha Sarovar Office
    url: https://cloud.tymly.in/status/1140
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Brigade Cosmopolis Clubhouse Entrance
    url: https://cloud.tymly.in/status/1141
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Brigade Cosmopolis Clubhouse End
    url: https://cloud.tymly.in/status/1145
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade A Block
    url: https://cloud.tymly.in/status/1153
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade B Block
    url: https://cloud.tymly.in/status/1154
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade C Block
    url: https://cloud.tymly.in/status/1155
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade D Block
    url: https://cloud.tymly.in/status/1156
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade E Block
    url: https://cloud.tymly.in/status/1157
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade F Block
    url: https://cloud.tymly.in/status/1159
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade G Block
    url: https://cloud.tymly.in/status/1158
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade H Block
    url: https://cloud.tymly.in/status/1161
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade I Block
    url: https://cloud.tymly.in/status/1160
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade J Block
    url: https://cloud.tymly.in/status/1162
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade K Block
    url: https://cloud.tymly.in/status/1163
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade L Block
    url: https://cloud.tymly.in/status/1164
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade M Block
    url: https://cloud.tymly.in/status/1003
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade N Block
    url: https://cloud.tymly.in/status/1165
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade O Block
    url: https://cloud.tymly.in/status/1166
    __dangerous__body_degraded: '{"status": "down"}'
  - name: Trifecta Esplanade P Block
    url: https://cloud.tymly.in/status/1017
    __dangerous__body_degraded: '{"status": "down"}'    
  - name: Trifecta Esplanade Common Area
    url: https://cloud.tymly.in/status/1174
    __dangerous__body_degraded: '{"status": "down"}'    
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /tymlymonitor
  logoUrl: https://tymly.in/img/tymly_logo.png
  name: tymly monitor
  introTitle: "**tymly monitor ** is the uptime monitor and status page for tymly smart boards."
  introMessage: This is the status page for tymly smart notice boards.
  navbar:
    - title: Status
      href: /
  js: "function contains(t,n){var e=document.querySelectorAll(t);return Array.prototype.filter.call(e,function(t){return RegExp(n).test(t.textContent)})}window.onload = function() {setTimeout(function(){foundDivsActiveIncidents=contains('section','Active Incidents');foundDivsActiveIncidents[0].remove();foundDivsPastIncidents=contains('section','Past Incidents');foundDivsPastIncidents[0].remove();}, 5000);}"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/10 * * * *"
